sudo: true
dist: xenial

git:
  depth: false

language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

cache: pip

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov==2.5.1 pytest-mock pytest-pep8 coveralls

script:
  - pytest --cov=autoscaler --pep8 autoscaler

jobs:
  include:
    - stage: deploy
      if: tag IS present
      python: 3.6
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$TRAVIS_REPO_SLUG" .
      - docker images
      - docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":latest
      - docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":"${TRAVIS_TAG}"
      - docker push "$TRAVIS_REPO_SLUG"

after_success:
  - coveralls
